# Generated by Django 3.2.7 on 2021-10-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialamount',
            name='_from',
            field=models.DecimalField(db_column='from', decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='initialamount',
            name='to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
